name: dork
description: Docker development container forking
dependencies:
  events: '>= 0.1.0'
  glob: ">=1.0.4 <2.0.0"
  args: ">=0.12.2+3 <0.13.0"
  yaml: ">=2.1.2 <3.0.0"
  http: ">=0.11.1+1 <0.12.0"
  di: ">=3.3.3 <4.0.0"
dev_dependencies:
  unittest: '>= 0.11.4'
  mock: '>= 0.11.0'
